require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

use_modular_headers!
use_frameworks!

target 'SkylabReactNativeClientExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'skylab-reactnative-client', :path => '../..'
  pod 'Skylab', :git => 'https://github.com/amplitude/skylab-ios-client', :tag => 'v1.0.1'
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  # TODO: Add back flipper support once the Skylab pod adds DEFINES_MODULE
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
